### ISSUE TITLE
How we get the selected date from the calender

### ISSUE THREAD

**Issue by gchokeen** [quanganh206/ionic2-calendar#4]
Hi,

I just tried this module in ionic project, I don't know How we get the selected date from the calendar? can you explain that please?

**Comment by quanganh206** [comment]
Hi @gchokeen you can find example here https://github.com/quanganh206/ionic2-calendar/blob/master/demo/esm/src/app/app.component.ts

**Comment by gchokeen** [comment]
Excellent! Thanks
